version: "3.9"

services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=travelogue'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/

volumes:
  postgresql: { }